//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlennSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFS_Alibi
    {
        public string GameId { get; set; }
        public string LennyLittle { get; set; }
        public string AlFarook { get; set; }
        public string PepePerez { get; set; }
        public string TonyRacheti { get; set; }
        public string MickeyOMalley { get; set; }
        public string MaxFineflugle { get; set; }
        public string RippRapp { get; set; }
        public string BusterBailey { get; set; }
        public string RockyRoll { get; set; }
        public string LingTong { get; set; }
        public string IvyLittle { get; set; }
        public string LucyTumble { get; set; }
        public string PiperPerez { get; set; }
        public string DinaRacheti { get; set; }
        public string EileenStellar { get; set; }
        public string JoanFineflugle { get; set; }
        public string RosePettle { get; set; }
        public string DorisDill { get; set; }
        public string CandyRoll { get; set; }
        public string SingWong { get; set; }
    
        public virtual CFS_MurderFacts CFS_MurderFacts { get; set; }
    }
}
