//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlennSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFS_WhoWasWhere
    {
        public string GameId { get; set; }
        public Nullable<int> ArtShowMaleIdOdd { get; set; }
        public Nullable<int> ArtShowMaleIdEven { get; set; }
        public Nullable<int> ArtShowFemaleIdOdd { get; set; }
        public Nullable<int> ArtShowFemaleIdEven { get; set; }
        public Nullable<int> BoxAtTheaterMaleIdOdd { get; set; }
        public Nullable<int> BoxAtTheaterMaleIdEven { get; set; }
        public Nullable<int> BoxAtTheaterFemaleIdOdd { get; set; }
        public Nullable<int> BoxAtTheaterFemaleIdEven { get; set; }
        public Nullable<int> CardPartyMaleIdOdd { get; set; }
        public Nullable<int> CardPartyMaleIdEven { get; set; }
        public Nullable<int> CardPartyFemaleIdOdd { get; set; }
        public Nullable<int> CardPartyFemaleIdEven { get; set; }
        public Nullable<int> DocksMaleIdOdd { get; set; }
        public Nullable<int> DocksMaleIdEven { get; set; }
        public Nullable<int> DocksFemaleIdOdd { get; set; }
        public Nullable<int> DocksFemaleIdEven { get; set; }
        public Nullable<int> EmbassyMaleIdOdd { get; set; }
        public Nullable<int> EmbassyMaleIdEven { get; set; }
        public Nullable<int> EmbassyFemaleIdOdd { get; set; }
        public Nullable<int> EmbassyFemaleIdEven { get; set; }
        public Nullable<int> FactoryMaleIdOdd { get; set; }
        public Nullable<int> FactoryMaleIdEven { get; set; }
        public Nullable<int> FactoryFemaleIdOdd { get; set; }
        public Nullable<int> FactoryFemaleIdEven { get; set; }
        public Nullable<int> ArtShowLocationId { get; set; }
        public Nullable<int> ArtShowAreaId { get; set; }
        public Nullable<int> BoxAtTheaterLocationId { get; set; }
        public Nullable<int> BoxAtTheaterAreaId { get; set; }
        public Nullable<int> CardPartyLocationId { get; set; }
        public Nullable<int> CardPartyAreaId { get; set; }
        public Nullable<int> DocksLocationId { get; set; }
        public Nullable<int> DocksAreaId { get; set; }
        public Nullable<int> EmbassyLocationId { get; set; }
        public Nullable<int> EmbassyAreaId { get; set; }
        public Nullable<int> FactoryLocationId { get; set; }
        public Nullable<int> FactoryAreaId { get; set; }
        public Nullable<int> ArtShowWeaponUsedId { get; set; }
        public Nullable<int> BoxAtTheaterWeaponUsedId { get; set; }
        public Nullable<int> CardPartyWeaponUsedId { get; set; }
        public Nullable<int> DocksWeaponUsedId { get; set; }
        public Nullable<int> EmbassyWeaponUsedId { get; set; }
        public Nullable<int> FactoryWeaponUsedId { get; set; }
    
        public virtual CFS_MurderFacts CFS_MurderFacts { get; set; }
    }
}
